### PR TITLE
Added handling of IAM profiles when accessing AWS API

### PR DESCRIPTION
**Pull request by marko-baric-travcorp**
With this change, IAM profiles can be used to access AWS API.
The tool now accepts 2 new arguments: "profileName" and "profilesLocation".
- profileName is the name od the IAM profile to used for AWS access
- profilesLocation is the path to the folder where all of the profiles are stored. This will be a file on CI server where all of the AWS profiles for our accounts will be stored.

If you want some more info how this works: http://blogs.aws.amazon.com/net/post/Tx1310VG2O81PSY/Referencing-Credentials-using-Profiles

### CODE REVIEW

**Comment by Jetski5822** [comment]
@joshski can you review

**Comment by joshski** [comment]
Great stuff @marko-baric-travcorp 

Two questions:

1) Do we really need to make either the "profilesLocation" or "profileName" mandatory? (this will break existing users)

2) Are the tests passing? :)

**Comment by marko-baric-travcorp** [comment]
I am working on test updates now.
I can make it backwards compatible if you wish, but is it really needed? Because every project will have to support several AWS accounts.

**Comment by marko-baric-travcorp** [comment]
@joshski Can you try to run unit tests? Stack creation fails on my box, I cannot figure out why.

**Comment by joshski** [comment]
Hi @marko-baric-travcorp, sorry but I'm not available to look at this today. Can you ask @DaveOps83 to help with your permissions issue?

**Comment by DaveOps83** [comment]
@marko-baric-travcorp @dmitry-livchak @joshski @Jetski5822 @PaulCampbell 

Why do we need elastic IPs for SSO? Why not just use the auto assigned public IP address of NAT? I have removed access to EIPs in TTC-DEV to prevent the Hybrid VPC from breaking.

**Comment by marko-baric-travcorp** [comment]
We don't need it. PushAndDeploy tool that we are using for AWS deployment has unit tests that create a stack with EIP. Which means that I cannot run unit tests.

**Comment by DaveOps83** [comment]
@marko-baric-travcorp what user are you using to run these tests?

**Comment by marko-baric-travcorp** [comment]
@DaveOps83 I use my AWS account

**Comment by DaveOps83** [comment]
As discussed lets remove the below from the VPC template file (example-windows-vpc-template.json)

"webServerEipAssociation": {
            "Type": "AWS::EC2::EIPAssociation",
            "Properties": {
                "AllocationId": {
                    "Fn::GetAtt": [
                        "webServerEIP",
                        "AllocationId"
                    ]
                },
                "InstanceId": {
                    "Ref": "webServer"
                }
            }
        },
        "internalApiServerEipAssociation": {
            "Type": "AWS::EC2::EIPAssociation",
            "Properties": {
                "AllocationId": {
                    "Fn::GetAtt": [
                        "internalApiServerEIP",
                        "AllocationId"
                    ]
                },
                "InstanceId": {
                    "Ref": "internalApiServer"
                }
            }
        }

**Comment by joshski** [comment]
Agreed, let's update the example used in the test so it doesn't make things we can't make anymore...

**Comment by marko-baric-travcorp** [comment]
I made the required changes. @joshski Please close this pull request. 
I am opening another one for additional features so both changes can be pushed to NuGet.

**Comment by DaveOps83** [comment]
@marko-baric-travcorp Cant you just push changes to this existing branch to update this pull request?

**Comment by marko-baric-travcorp** [comment]
@DaveOps83 I did. Now Josh needs to close pull request and merge it to "master". And someone (you maybe?) must push this change as a new release to NuGet.

**Comment by DaveOps83** [comment]
Ah, I get it now sorry I misunderstood.

We should probably add a job configuration to TeamCity for this repo so it can push to Nuget automagically.

**Comment by DaveOps83** [comment]
@marko-baric-travcorp @bcipri @dmitry-livchak 

Guys, if we are adding new arguments can you please update the README to include these? I can't see it in the list of changed files.

**Comment by DaveOps83** [comment]
@marko-baric-travcorp, @joshski

Can you please remove the AWS API credentials (credentials file) from this branch. This is a public repository which we have open sourced and AWS keys should never be committed to GitHub. I have reissued your access keys and sent them to you in a separate email.

**Comment by marko-baric-travcorp** [comment]
@DaveOps83 My mistake, I wasn't paying attention to this. I will remove the file.

**Comment by DaveOps83** [comment]
Thanks! Please look out for this when working with other people and educate them if necessary.

**Comment by DaveOps83** [comment]
Does the README not need updating?

**Pull request closed without merging**
